---
version: "2.11"
name: Simple Scheduler
description: Simple timer on weekly base
slug: simplescheduler
url: https://github.com/smarthomekh/hasaddon/tree/main/SimpleScheduler
codenotary: smarthome-simpleschedule
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: true
ingress: true
panel_admin: false
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw
